# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  raincatcher_c_config = debug_x64
endif
ifeq ($(config),debug_x86)
  raylib_config = debug_x86
  raincatcher_c_config = debug_x86
endif
ifeq ($(config),debug.dll_x64)
  raylib_config = debug.dll_x64
  raincatcher_c_config = debug.dll_x64
endif
ifeq ($(config),debug.dll_x86)
  raylib_config = debug.dll_x86
  raincatcher_c_config = debug.dll_x86
endif
ifeq ($(config),release_x64)
  raylib_config = release_x64
  raincatcher_c_config = release_x64
endif
ifeq ($(config),release_x86)
  raylib_config = release_x86
  raincatcher_c_config = release_x86
endif
ifeq ($(config),release.dll_x64)
  raylib_config = release.dll_x64
  raincatcher_c_config = release.dll_x64
endif
ifeq ($(config),release.dll_x86)
  raylib_config = release.dll_x86
  raincatcher_c_config = release.dll_x86
endif

PROJECTS := raylib raincatcher-c

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C build -f Makefile config=$(raylib_config)
endif

raincatcher-c: raylib
ifneq (,$(raincatcher_c_config))
	@echo "==== Building raincatcher-c ($(raincatcher_c_config)) ===="
	@${MAKE} --no-print-directory -C raincatcher-c -f Makefile config=$(raincatcher_c_config)
endif

clean:
	@${MAKE} --no-print-directory -C build -f Makefile clean
	@${MAKE} --no-print-directory -C raincatcher-c -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug.dll_x64"
	@echo "  debug.dll_x86"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release.dll_x64"
	@echo "  release.dll_x86"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   raincatcher-c"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"